#!/usr/bin/env bash
# gen-manifest.sh: regenerate two artifacts from each guidance/*.md
# "Load when:" header (single source of truth):
#   1. the guidance-file table in MANIFEST.md   (full catalog, all files)
#   2. guidance/INDEX.md                        (hot subset, injected at SessionStart)
# Usage: gen-manifest.sh          # rewrite both in place
#        gen-manifest.sh --check  # exit 1 if either is stale (no write)
set -euo pipefail
cd "$(dirname "$0")/.."

python3 - "${1:-}" <<'EOF'
import os, re, sys
check = sys.argv[1] == '--check'

# Guidance files that exist and stay on disk, but are NOT advertised at
# SessionStart. Cut 2026-08-03: zero reads (Read tool AND bash cat/grep) across
# ~4200 session logs, and referenced by zero skills. They remain in MANIFEST.md,
# so they are still discoverable on demand: they just no longer pay rent in
# every session's context. Re-promote by deleting a line here.
# Public set is curated: every file shipped is worth advertising, so nothing is cold.
COLD = set()

HEADER_RE = re.compile(r'<!-- Load when: (.+?) -->')

def load_when(fname):
    """Scan the first few lines, not just line 1: several files carry a
    version/last-updated comment above the Load-when header."""
    if fname == 'ESSENTIAL.md':
        return 'AUTO-LOADED at SessionStart: top most-violated rules'
    with open(f'guidance/{fname}') as fh:
        for _ in range(5):
            line = fh.readline()
            if not line:
                break
            m = HEADER_RE.search(line)
            if m:
                return m.group(1).strip()
    return 'MISSING Load-when header: add one'

files = sorted(f for f in os.listdir('guidance')
               if f.endswith('.md') and f != 'INDEX.md')
descs = {f: load_when(f) for f in files}
missing = [f for f in files if descs[f].startswith('MISSING')]

# ---- 1. MANIFEST.md: full catalog, cold entries marked ----
rows = []
for f in files:
    mark = ' _(cold: not indexed at SessionStart)_' if f in COLD else ''
    rows.append(f'| `guidance/{f}` | {descs[f]}{mark} |')
block = '\n'.join(
    ['<!-- BEGIN GENERATED guidance table (scripts/gen-manifest.sh) -->',
     f'{len(rows)} guidance files ({len(rows) - len(COLD)} indexed at SessionStart '
     f'via `guidance/INDEX.md`, {len(COLD)} cold). Descriptions come from each '
     'file\'s "Load when:" header.',
     '', '| File | Load when |', '|---|---|'] + rows +
    ['<!-- END GENERATED -->'])
manifest_old = open('MANIFEST.md').read()
if '<!-- BEGIN GENERATED' not in manifest_old:
    sys.exit('MANIFEST.md has no generated-block markers; add them first')
manifest_new = re.sub(r'<!-- BEGIN GENERATED guidance table.*?<!-- END GENERATED -->',
                      lambda _: block, manifest_old, flags=re.S)

# ---- 2. guidance/INDEX.md: hot subset, cat'd into every session ----
hot = [f for f in files if f not in COLD and f != 'ESSENTIAL.md']
lines = ['<!-- GENERATED by scripts/gen-manifest.sh: do not edit by hand -->',
         '# Guidance File Index', '',
         '**Always loaded at SessionStart:** `guidance/ESSENTIAL.md` '
         '(top most-violated rules).',
         'Load on-demand based on the current task:']
lines += [f'- `guidance/{f}` -- {descs[f]}' for f in hot]
if COLD:
    lines += ['',
              f'Not indexed ({len(COLD)} cold files: '
              + ', '.join(sorted(c[:-3] for c in COLD))
              + '). They still exist and still work; see `MANIFEST.md` for the '
                'full catalog if nothing above fits.']
index_new = '\n'.join(lines) + '\n'
index_path = 'guidance/INDEX.md'
index_old = open(index_path).read() if os.path.exists(index_path) else ''

if check:
    stale = [n for n, o, w in (('MANIFEST.md', manifest_old, manifest_new),
                               (index_path, index_old, index_new)) if o != w]
    if missing:
        print('MISSING Load-when header: ' + ', '.join(missing), file=sys.stderr)
    if stale:
        print('stale: ' + ', '.join(stale), file=sys.stderr)
    sys.exit(1 if stale else 0)

open('MANIFEST.md', 'w').write(manifest_new)
open(index_path, 'w').write(index_new)
print(f'MANIFEST.md: {len(files)} files  |  {index_path}: {len(hot)} indexed, '
      f'{len(COLD)} cold')
if missing:
    print('WARN missing Load-when header: ' + ', '.join(missing), file=sys.stderr)
EOF
